name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: nautilus-build

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle to support advanced caching
        uses: gradle/gradle-build-action@v2.11.1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release with Gradle
        run: ./gradlew assemble check

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/**/*.xml'
